### ISSUE TITLE
Better testing strategy (more mocks!)

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#103]
_From @johnnyshields on April 20, 2014 9:46_

Currently most of the tests in this repo require actually connecting to the Gmail service. This is problematic witha  large number of tests because:
1) Gmail can raise "TooManyConnection" errors
2) it's slow

I propose instead we break tests into `unit` and `integration` folders, and use mocks (i.e. stubbed objects) in the `unit` folder. The integration tests should be a minimal subset of tests required to verify core API connectivity works.

I'm glad to take a lead on this, but am hesitant to do so as the maintenance of this gem is currently in the twilight zone.

_Copied from original issue: nu7hatch/gmail#103_

**Comment by johnnyshields** [comment]
_From @webcracy on April 20, 2014 10:1_

@johnnyshields :+1: , I find that better as well. I'd be happy to pull it into my own fork (that I sometimes use instead of the gem), so do ping me for contributions and/or testing. 

It would be great to have email mocks will different character exotisms as well. Anyone else into this?

And I believe @nu7hatch will find a solution out of the twilight zone soon, like he said; in any case, I don't think this particular effort would be lost in limbo -- the continuing fork could pick it up.

**Comment by johnnyshields** [comment]
_From @jgrevich on April 21, 2014 19:46_

@johnnyshields Great ideas. I'd would like to focus on this as well.  I will start to create issues so we can clean up our test suite.  We should also integrate with things like https://coveralls.io/ and https://codeclimate.com/.

**Comment by johnnyshields** [comment]
Just a note on this, I think we should introduce a dev dependency on https://github.com/bblimke/webmock so we can guarantee a stable API response, at least for Travis CI.  I'll look into it at some point.

**Comment by bootstraponline** [comment]
:+1: for webmock / [vcr](https://github.com/vcr/vcr)
