### ISSUE TITLE
Fix delete method for message

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#120]
_From @tdeo on November 19, 2014 15:15_

Deleting a mail was stuck in a loop. This commit fixes it

_Copied from original issue: nu7hatch/gmail/pull/120_

**Comment by bootstraponline** [comment]
_From @tdeo on November 19, 2014 15:16_

Additionaly, I added support for French GMail trash. New languages can be added easily

**Comment by johnnyshields** [comment]
See PR #134
