### ISSUE TITLE
connect() no longer invokes the block in 0.4.2

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#121]
_From @weshatheleopard on November 21, 2014 0:36_

```
> Gmail.connect("my_login", "my_password") do |gmail|
>   puts "I'M INSIDE THE BLOCK!"
> end
=> #<Gmail::Client0x7cb9da8 ("my_login") connected>
>
```

_Copied from original issue: nu7hatch/gmail#121_

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 15, 2015 13:54_

Any help with raise a PR fix w/ a spec for this would be greatly appreciated.

**Comment by johnnyshields** [comment]
@weshatheleopard can you please raise a PR with a spec demonstrating the problem?

**Comment by weshatheleopard** [comment]
The sample code is provided above. Try it with your own email account. Sorry, I do not have time to create the necessary mocks for a proper spec.
