### ISSUE TITLE
Fix tests on Travis

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#129]
_From @bootstraponline on January 14, 2015 2:3_

Tests are kind of limited if they're not run automatically in CI. Travis has the ability to [encrypt credentials](http://docs.travis-ci.com/user/encryption-keys/) which would enable the gmail specs to run automatically.

_Copied from original issue: nu7hatch/gmail#129_

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 15, 2015 4:19_

I've merged in my earlier PR which includes Travis support. Travis encryption is not ideal since it doesn't work with Pull Requests.

**Comment by bootstraponline** [comment]
sounds good. :+1:

**Comment by bootstraponline** [comment]
I think the integration hook isn't setup because there are no builds on travis.

https://travis-ci.org/nu7hatch/gmail

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 15, 2015 16:23_

We need @nu7hatch to setup Travis since it requires repo owner permission, and he's hard to track down. I've raised #131 to move to a new repo which we maintain, if all are agreed will do soon.

**Comment by johnnyshields** [comment]
Repo now migrated, next step is to actually fix the tests in a PR.

**Comment by bootstraponline** [comment]
I'm looking at some of the errors on Travis such as:

>  Couldn't login to given GMail account: ki0zvkyi1yzgy7xu4f4dh46nqrcecm@gmail.com (Too many simultaneous connections. (Failure))

and I think the only way we're going to get stable results is via mocking.

**Comment by johnnyshields** [comment]
Yeah I agree. It would be nice if we could run tests in "mock mode" and "real mode" via an environment variable. Then could have "real mode" be an allowed failure on Travis, so we can at least check it from time to time.

**Comment by bootstraponline** [comment]
I think #141 is on the right track. :+1: 

To set expectations, I don't anticipate having much time to contribute to the gem. I'm using it at work for one project and am interested in making sure that the gem continues to work reliably.

**Comment by bootstraponline** [comment]
[GoGaRuCo 2014- Taking over Someone Else's Open-Source Projects](https://www.youtube.com/watch?v=8ijzefV-B7U) - an interesting presentation. It'd be great if we had a lead dev.

**Comment by johnnyshields** [comment]
Good talk, a lot of good ideas in one place. I actually know this guy via
Github and I've helped him with a few project takeovers, one of them being
https://github.com/aq1018/mongoid-history.

Thanks for your help!

**Comment by johnnyshields** [comment]
I'm going to close this issue in favor of #141 and the various other open pull requests which contain specs.
