### ISSUE TITLE
Move gem to new location gmailgem/gmail

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#131]
_From @johnnyshields on January 15, 2015 10:47_

I've registered organization "gmailgem". If it's ok with everyone let's move the repo to gmailgem/gmail and make that official. Among reasons for doing this is that things like Travis CI require approval from @nu7hatch, there's bound to be more things in the future so easiest just to move the gem. Any comments? @jgrevich @webcracy @nu7hatch

_Copied from original issue: nu7hatch/gmail#131_

**Comment by bootstraponline** [comment]
I agree, let's move to gmailgem.

**Comment by bootstraponline** [comment]
_From @jcarbo on January 17, 2015 0:53_

@johnnyshields first of all this is awesome! Thanks for all the work merging all those PRs into the new repo.

@johnnyshields @bootstraponline @webcracy who owns the /gmailgem/gmail repo? Can you [enable issues on that fork](http://programmers.stackexchange.com/a/179470) so that we can use that as the main repo?

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 17, 2015 8:13_

@jcarbo I've contacted Github to see if they can migrate the issues over to the new repo. If not we can do so manually. Have also enabled you as a collaborator for gmailgem group.

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 17, 2015 9:40_

@jcarbo so, since none of us are admins (aside from @nu7hatch) on this repo we cannot transfer. I've enabled issue tracking on that repo.

It would be helpful if someone could attempt to copy issues via the Github API from nu7hatch repo to the new repo (see API docs here: https://developer.github.com/v3/issues/). It would be good as people often search issues for answers.

I will look into merging the remaining pull requests in the next week. It looks like they can be easily merged. Then we can close down this repo and put a "moved" message in the README.

**Comment by bootstraponline** [comment]
can someone make me a collaborator on this repo? I can't close the issues that I'm migrating.

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 17, 2015 17:41_

@bootstraponline I'll take care of closing them. Thanks so much for migrating. (None of us have access to make you a collaborator on this repo except nu7hatch who is awol)

**Comment by johnnyshields** [comment]
This is DONE!
