### ISSUE TITLE
Net::IMAP::BadResponseError: Unknown command b69mb27045186qhb

### ISSUE THREAD

**Issue by hubrix** [gmailgem/gmail#151]
/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/imap.rb:1158 in "get_tagged_response"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/imap.rb:1210 in "block in send_command"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211 in "mon_synchronize"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/imap.rb:1192 in "send_command"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/imap.rb:453 in "block in select"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211 in "mon_synchronize"
/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/imap.rb:451 in "select"
/vendor/bundle/ruby/2.1.0/bundler/gems/gmail-c406b48730f8/lib/gmail/client/base.rb:207 in "switch_to_mailbox"
/vendor/bundle/ruby/2.1.0/bundler/gems/gmail-c406b48730f8/lib/gmail/client/base.rb:164 in "block in mailbox"
/vendor/bundle/ruby/2.1.0/bundler/gems/gmail-c406b48730f8/lib/gmail/client/base.rb:161 in "synchronize"
/vendor/bundle/ruby/2.1.0/bundler/gems/gmail-c406b48730f8/lib/gmail/client/base.rb:161 in "mailbox"

**Comment by johnnyshields** [comment]
As the name implies (bad response) this error may be coming from Gmail itself. I see these every now and then sporadically in my app; I just catch and and ignore.

I'm closing this for now unless there is further evidence that GmailGem is doing something wrong.
