### ISSUE TITLE
Drop rubinius tests from Travis auto run

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#154]
Rubinius is always failing. As the failures are automatically ignored, I don't see the value in running them. Does anyone use the gmail gem on rubinius?

**Comment by johnnyshields** [comment]
I think it's useful to see if someone does want to use with Rubinius, and will encourage them potentially to fix it. No harm in this so I propose to leave it.

**Comment by bootstraponline** [comment]
ok, makes sense.
