### ISSUE TITLE
Behavior of `archive!` method has changed

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#160]
@jcarbo in this commit, you changed how `archive!` behaves: https://github.com/gmailgem/gmail/commit/94ba0c5e6d4a907172f0d8ca3ee4bfdd8ebd0146

In version 0.4.x and earlier, archive would move a message out of the Inbox entirely. In the new version, it seems that the messages stay in the Inbox AND appear in the archive (All Mail) with an "Inbox" label. Best to test manually to see the difference.

My app actually relies on the message to be out of the inbox, as I have a batch job which moves them out of the inbox after processing.

**Comment by johnnyshields** [comment]
Looks like the main problem is that `remove_label("\\Inbox")` does not work for me.

**Comment by jcarbo** [comment]
I tested this by logging into gmail using the credentials in accounts.yml
and using he methods in the ruby console. We can/should probably add some
more extensive specs around this.


On Jan 26, 2015, at 8:13 PM, Johnny Shields <notifications@github.com>
wrote:

Looks like the main problem is that remove_label("\\Inbox") does not work
for me.

—
Reply to this email directly or view it on GitHub
<https://github.com/gmailgem/gmail/issues/160#issuecomment-71572689>.

**Comment by mateomurphy** [comment]
Just ran into this; The `\Inbox` is not showing up in the list of labels that messages in the inbox have, which may be why it can't be removed. Could be an issue on gmail's side...

**Comment by mateomurphy** [comment]
Did some messing around, and finally got something working. From what I can understand, you can't remove the `\Inbox` label from within the Inbox; you need to be in another mailbox.

I got things working by scanning through my inbox with `mailbox('[Gmail]/All Mail').emails(gm: 'in:inbox')`.

**Comment by subimage** [comment]
Weird...will this ever get fixed, then or docs updated?

**Comment by johnnyshields** [comment]
The old behavior is the correct one, the current behavior is incorrect. If you are able to help chase down this bug it would be greatly appreciated.

**Comment by mateomurphy** [comment]
I'm willing to do some work on this. There are two approaches I can see:

1) Stick to IMAP semantics for copying and moving messages, reverting to the previous code and fixing as appropriate

2) Fully embrace Gmails approach, and use labels exclusively rather than the mix of mailboxes and labels being used now. Thats means that code like `gmail.label("Faxes").emails` would actually do `mailbox('[Gmail]/All Mail').emails(label: 'Faxes')`.

Any thoughts on this?

**Comment by johnnyshields** [comment]
I'd favor the second approach. My main question would be if this is compatible with non-English locale mailboxes? @jcarbo your thoughts?

**Comment by mateomurphy** [comment]
As long as we use the special folder names, it should work in all locales? Easy to test, in any case

**Comment by johnnyshields** [comment]
I don't know much about it. Maybe this PR will be useful? https://github.com/nu7hatch/gmail/pull/83

**Comment by asiniy** [comment]
Using this PR: https://github.com/gmailgem/gmail/pull/195

``` ruby
message_id = email_with_label_we_need_to_remove.message_id

@gmail_account.mailbox('[Gmail]/All Mail').find(message_id: message_id.to_s).first.remove_label("Label we need to remove")
```

I'll write good PR for this functionality, but this one PR should be merged first: https://github.com/gmailgem/gmail/pull/186

**Comment by chrisbrasington** [comment]
Appears to still be an issue. I can't use .acrhive!, but read! and delete! work fine. I'll give move_to a shot as a workaround, thanks.

**Comment by johnnyshields** [comment]
It would be much appreciated if someone can raise a PR to properly fix `.archive!`

**Comment by athirn** [comment]
Just ran into this issue.  Unfortunately, with large mailboxes, `mailbox('[Gmail]/All Mail').emails(label: 'Inbox')` and `mailbox('[Gmail]/All Mail').find(message_id: message_id).first` has major performance issues.  On my mailbox, 'All Mail' has 750K messages and looping through each message in a filter result take 30 seconds for each message.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
