### ISSUE TITLE
Is it possible to reply to an email?

### ISSUE THREAD

**Issue by zoopyserg** [gmailgem/gmail#164]
I did `email.reply`
And it made an instance of Gmail::Message. 
It even accepts a block correctly.
But when I do `gmail.deliver! email.reply` it gives this error:

`Gmail::Client::DeliveryError: Couldn't deliver email: Connection refused - connect(2) for "localhost" port 25`

**Comment by zoopyserg** [comment]
Right now use this:
````ruby
        reply = email.reply do
          subject "Re: #{email.subject}"
          body "reply text"
        end

        new_email = gmail.compose do
          to reply.to
          subject reply.subject
          in_reply_to reply.in_reply_to
          references reply.references
          body reply.body.raw_source
        end
````

**Comment by johnnyshields** [comment]
I don't have this use case. @gmailgem/owners can anybody assist?

**Comment by andrewparrish** [comment]
A suggestion: while replying is not really a built in feature, there is a way to essentially make gmail believe that a message is a direct reply to a previously received message.

Let's say for example I want to reply to the last message I've received in my inbox:

```
gmail = Gmail.connect("myusername", "mypassword")
email_to_reply_to = gmail.inbox.all.last

```
We now need to use that email to get a couple important indicators that gmail will use to know its a reply. 

There are the message_id, and the subject. Important! If the original message's subject is blank, the reply should not include a subject either.

```
reply_to_id = "<#{email_to_reply_to.message.message_id}>"
email_subject = email_to_reply_to.subject

if subject.nil?
    gmail.deliver do
        to "reply_to_id address here"
        in_reply_to reply_to_id
        body "Your message"
    end
else
    reply_subject = "Re: #{email_subject}"
    gmail.deliver do
        to "reply_to_id address here"
        in_reply_to reply_to_id
        subject reply_subject
        body "Your message here"
    end
end

```

Hope that helps!

**Comment by amoludage** [comment]
Hello @andrewparrish 
 
I have tried your solution, but it fails because of `reply_to_id` which you find from `email_to_reply_to.message.message_id`.

For this I received the mail from `Mail Delivery Subsystem <mailer-daemon@googlemail.com>` and the mail contents are as follows,

    Delivery to the following recipient failed permanently:

     589732-513-455B-86FF-E37BBDE9@gmail.com

    Technical details of permanent failure:
    Google tried to deliver your message, but it was rejected by the server for the recipient domain           
    gmail.com by gmail-smtp-in.l.google.com.


To send reply you need to change `reply_to_id`  to ` email_to_reply_to.message.from ` that is instead of `message_id` use `from`, and also change `email_subject` to  `email_to_reply_to.message.subject` instead of `email_to_reply_to.subject`

Example: 

    gmail = Gmail.connect("myusername", "mypassword")
    email_to_reply_to = gmail.inbox.all.last

    reply_to_id = email_to_reply_to.message.from
    email_subject = email_to_reply_to.message.subject

    gmail.deliver do
        to reply_to_id
        subject "Re: #{email_subject}"
        body "Your reply message here"
    end

This example is perfectly works for me.

may this helps for you.

Thanks.
