### ISSUE TITLE
Strange behaviour attaching files

### ISSUE THREAD

**Issue by romgrod** [gmailgem/gmail#166]
Hi,

I am facing a strange behaviour and I cannot find why it happens. Excuse me if the answer is obvius, but I cannot get it.
The thing is that when I am composing an email and attach a file passing the path to the file it is attached twice. So, I receive the email with two files attached and both are the same file.
This is the piece of code I am using

email = @email.compose do
            to $CONF.recipients
            subject message_subject
            text_part do
              body message_body
            end
            html_part do
              $LOGGER.debug "Notification: Attaching report file (#{path_to_file})"
              content_type 'text/html; charset=UTF-8'
              body "<p>#{message_body}</p>"
            end
            add_file path_to_file
          end

It almost exact the same as the example. But I cannot find the reason why it is happening.

Thanks in advance

**Comment by johnnyshields** [comment]
I don't use file attachments. @gmailgem/owners can anybody assist?

**Comment by johnnyshields** [comment]
The [Mail gem](https://github.com/mikel/mail) does the heavy lifting of attachment handling, so if there is an issue on the Ruby side it's likely in Mail.

Will reopen if you can come back with a smoking gun that Gmail gem is doing something wrong.
