### ISSUE TITLE
remove_label bug

### ISSUE THREAD

**Issue by subimage** [gmailgem/gmail#168]
Inside of a mailbox loop I can't remove the label to effectively "move" a message.

``` ruby
@gmail.mailbox(@label_incoming).emails

gmail = Gmail.connect(user, pass)
gmail.mailbox('foo').emails.each do |m|
  m.remove_label('foo')
  m.add_label('bar')
end
```

Running this loop I end up with all emails labeled BOTH foo and bar.

I can remove extra labels, just not the one in 'mailbox'.

`move_to` also doesn't work within the same context. Ideas?

**Comment by mateomurphy** [comment]
see #160 , I posted a workaround there

**Comment by asiniy** [comment]
@mateomurphy huge thanks!

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
