### ISSUE TITLE
WARNING: Could not parse (and so ignoring) 'Content-Type: multipart/alternative... warnings

### ISSUE THREAD

**Issue by tomduncalf** [gmailgem/gmail#169]
We see warning messages like:

```
WARNING: Could not parse (and so ignoring) 'Content-Type: multipart/alternative;boundary=75f71998-837b-41e1-90a0-df1e3d14d5db'
WARNING: Could not parse (and so ignoring) 'Content-Type: multipart/alternative;boundary=75f71998-837b-41e1-90a0-df1e3d14d5db'
WARNING: Could not parse (and so ignoring) 'Content-Type: multipart/alternative;boundary=75f71998-837b-41e1-90a0-df1e3d14d5db'
```

when accessing mails from Gmail - is there any way to silence these? Everything works fine otherwise - thanks for the great gem.

**Comment by johnnyshields** [comment]
These errors are coming from the [Mail](https://github.com/mikel/mail) gem:

https://github.com/mikel/mail/blob/master/lib/mail/field.rb#L219

It looks like he's using STDERR, which is bad--should allow user to specify a custom logger. I'm closing this as it's not our issue.

**Comment by tomduncalf** [comment]
Thanks Johnny - I forgot to update this issue with our solution for the issue, for future reference, we just redirect stderr temporarily while working with the gmail gem. Not ideal as you could be losing other errors in the process, but it does the trick for now. 

```
$stderr.reopen('/dev/null', 'w')
emails = gmail.inbox.emails(email_search_params)
$stderr = STDERR
```

Obviously you could encapsulate this pattern in a reusable way if you do lots of email access.

**Comment by johnnyshields** [comment]
Cool, thanks! I filed an issue with Mail here: https://github.com/mikel/mail/issues/873
