### ISSUE TITLE
SSL Issue when using gmail gem

### ISSUE THREAD

**Issue by ajcurtin** [gmailgem/gmail#170]
I am getting the follow ssl error when trying to use the gmail gem to automatically sign into gmail accounts for testing purposes:

OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A 

Looking around offered very little in help.

Thanks

**Comment by johnnyshields** [comment]
I do not believe this issue is specific to Gmail gem. Please see:
( https://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read
