### ISSUE TITLE
witing attachment from file give me additional new line characters after each line

### ISSUE THREAD

**Issue by Cansiano** [gmailgem/gmail#172]
when saving the attachment:
newFile = File.open(File.join(dir, f.filename), "w")
					contents = f.body.decoded
					newFile	<< contents
newFile.close

I see added new line character after each line in comperison with attachment.
I tried to change encoding in begging of script or while saving but it didn't help.

**Comment by johnnyshields** [comment]
The [Mail gem](https://github.com/mikel/mail) does the heavy lifting of attachment handling, so if there is an issue on the Ruby side it's likely in Mail. I will reopen this issue if you can come back with evidence that Gmail gem is doing something wrong.
