### ISSUE TITLE
Another attachments issue... header parsing problem

### ISSUE THREAD

**Issue by yebyen** [gmailgem/gmail#173]
I will start by saying I have not read the relevant RFC about correct mail headers and how they are terminated, I have already assumed that gmail gem is the one who has implemented the RFC correctly and this issue is about reacting proactively to attachments transmitted by badly behaving MTAs.

I noticed that when messages come through our message processing pipeline, which is mainly watching for attachments, and if it doesn't find any, applying the "no_attachments" label... sometimes mail with attachments gets the `no_attachments` treatment, and in each of these cases I checked so far there is a double line break in their mail header after `References` and before `Accept-Language` header, like this:

```
Date: Wed, 3 Jun 2015 17:58:42 +0000
Message-ID: <12345@ABCDE.namprd05.prod.outlook.com>
References: <24567@ABCDE.namprd05.prod.outlook.com>
  
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
```

I have checked in Gmail interface proper, and it is able to recognize the attachments on this mail, and I have checked the attachments property of the message object as gmail gem parses it, and I get `attachments.size==0`, an empty array showing no attachments.

I noticed a correlation between these events and I guessed that Gmail proper has already noticed this bad behavior and worked around it; I wonder if anyone who knows about the gmail gem's handling of attachments can say for sure that as I suspected, it is A causing B, and it is really a badly behaving MTA...

**Comment by yebyen** [comment]
Someone informed me today that an empty line with four spaces at the front is a valid way for a mail header to say a header content has been continued on the next line.  There is no continuation of the references header, but Gmail proper seems to understand, it seems like gmail gem is the one that has the problem here.

**Comment by johnnyshields** [comment]
@yebyen the Gmail gem uses the [Mail gem](https://github.com/mikel/mail) under the hood for the processing of attachments--we aren't getting into the mess of protocol handling.

I'm going to close this issue as I suspect the Mail gem is the culprit, will reopen if you can come back with a smoking gun that Gmail gem is doing something wrong.
