### ISSUE TITLE
Problem sending mail to multiple people

### ISSUE THREAD

**Issue by Kyrremann** [gmailgem/gmail#174]
I'm having trouble sending e-mail to multiple people. There is no errors in the log, but I don't get the e-mail on the other end. I'm pretty sure that there is an error in the list of e-mails, but I'm having trouble debugging it without any errors.
Is it possible to add more logging/debugging?

Also, when I paste it into Outlook or Gmail, all e-mails are added. It's 31 e-mails.

**Comment by BryanH** [comment]
Please post some code of what you've tried

**Comment by Kyrremann** [comment]
You can see the code here: https://github.com/Ciber-Norge/CiberSquash/blob/master/scheduler.rb#L71
But I'm pasting it here too:
```ruby
def send_email
  Gmail.connect!(GMAIL_USERNAME, GMAIL_PASSWORD) { | gmail | 
    gmail.deliver do
      to MAILING_LIST
      subject ENV['MAIL_SUBJECT']
      text_part do
        content_type 'text/text; charset=UTF-8'
        body ENV['MAIL_BODY_TEXT']
      end
      html_part do
        content_type 'text/html; charset=UTF-8'
        body ENV['MAIL_BODY_HTML']
      end
    end
  }
end
```

The variable `MAILING_LIST` is a semicolon seperated list.
`"Name, Some" <some_name@our_company.com>;`

**Comment by amoludage** [comment]
@BryanH  There is problem with your solution, the MAILING_LIST has missing double quotes `"`
The MAILING_LIST should be as following.


    
      MAILING_LIST = [

         "Name, Some <some_name@example.com>", 

         "Else, One <one_else@example.com>",  

         "Person, Another <another_person@example.com>"
      ] 


@Kyrremann  you can also specify only mail_ids to MAILING_LIST.

Example: 

`
    MAILING_LIST = [
         "test1@gmail.com", "test2@gmail.com", "test3@gmail.com"
    ]
`

**Comment by BryanH** [comment]
@amoludage You're absolutely right; thanks for the correction

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
