### ISSUE TITLE
email.attachments == [] when email with image is sent from Apple Mail app

### ISSUE THREAD

**Issue by petervojtek** [gmailgem/gmail#184]
when email is sent from apple Mail app to gmail with image in attachment, the image is properly visible in gmail gui, but gmail gem tells that `email.attachments` is an empty array.
Emails with attachments sent from other mail apps work properly.

**Comment by petervojtek** [comment]
maybe [this](http://www.anatomised.com/images-sent-mac-email-attachments-appearing-embedded-pc/) is the root of the problem?

**Comment by johnnyshields** [comment]
Closing this issue as:
1) @petervojtek's link is a likely culprit
2) The [Mail gem](https://github.com/mikel/mail) does the heavy lifting of attachment handling, so if there is an issue on the Ruby side it's likely in Mail.

Will reopen if you can come back with a smoking gun that Gmail gem is doing something wrong.
