### ISSUE TITLE
archive!

### ISSUE THREAD

**Issue by nancyhawa** [gmailgem/gmail#185]
I'm having trouble with the archive! method.  unstar!, star!, and delete! all work fine, but archive! seems to have no effect at all.

**Comment by russmac** [comment]
I'm having the same issue, no effect.

**Comment by nancyhawa** [comment]
Someone else on the issues board found a workaround.  If you access the email from outside the inbox you can archive it.  I'm now having issues with delete! being inconsistent.

**Comment by amoludage** [comment]
Please check #160 issue for reference.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
