### ISSUE TITLE
Any plan to support the Gmail  Push Notifications?

### ISSUE THREAD

**Issue by flyeven** [gmailgem/gmail#187]
Hi thanks for your help. Does the gem support Gmail‘s new Push Notifications?

https://developers.google.com/gmail/api/guides/push

https://github.com/nihalshah/Integrate-Gmail-in-Ruby

**Comment by johnnyshields** [comment]
I don't think there's a strong need for these notifications in this Gem. We're primarily focused on receiving entire messages using the IMAP protocol, and we already support a way to idle and listen for new messages.
