### ISSUE TITLE
Time in :before and :after filters

### ISSUE THREAD

**Issue by psychoche** [gmailgem/gmail#198]
Hi!

I'm trying to write a simple script to count messages in the last hour:

`gmail.inbox.count(:after => (Time.now - 3600))`

But I always get messages count limited for today, not for last hour.  Is it possible to use time in filters and not only date?

**Comment by psychoche** [comment]
Sorry for my question. I've read IMAP documentation and now I know this is impossible.

**Comment by MasterRoot24** [comment]
I've just had this problem and was about to raise an issue. I think I might add a note to the README. I wonder how many others have had this issue, though.
