### ISSUE TITLE
Not setting subject correctly for some reason.

### ISSUE THREAD

**Issue by ilovemysillybanana** [gmailgem/gmail#200]
![forgithub](https://cloud.githubusercontent.com/assets/9522399/11223049/d6324386-8d3b-11e5-86b4-ebb8b6e968bd.png)

Here's the code I'm using it doesn't give any errors, it just always makes the emails be with no subject.

**Comment by grant-olson** [comment]
It's probably trying to grab the `@email_subject` from the wrong context, where it doesn't exist, and thus returns nil which generates an empty string. Before gmail.deliver do `email_subject = @email_subject` and then use the local variable instead of the instance variable inside the block.

**Comment by ilovemysillybanana** [comment]
Do you see above where it says:

puts "subject :#{@email_subject}"

That part works, it prints it out as expected. I tried appending to it and it doesn't work.  Here I posted the whole code as a gist, it's rather short if you could take a look maybe you'll be to see what I'm talking about.

https://gist.github.com/ilovemysillybanana/abc87147d694d03fc08d
