### ISSUE TITLE
body gmail can't create new line with \n...

### ISSUE THREAD

**Issue by rcspam** [gmailgem/gmail#201]
Hi,
Perhaps i'm wrong, but '\n' have no effect on body text_part.

Example:
With...
```
gmail.compose do
   to "someone@somewhere.com"
   subject "Subject"
   text_part do
    body "Some text \n Some other \n "
   end
```
... mail is arrived with \n in the body.

Is this a bug or must i use html_part

**Comment by johnnyshields** [comment]
This is standard behavior of the email format. According to http://www.faqs.org/rfcs/rfc2822.html please try using `\r\n` (also called "carriage-return/line-feed" or "CRLF")

**Comment by rcspam** [comment]
No ```\r\n``` has not effect.
Is there a way to pass a normal text to body :( ?

**Comment by johnnyshields** [comment]
@rcspam please refer to Mail gem (see readme)
