### ISSUE TITLE
Methods doesn't work properly

### ISSUE THREAD

**Issue by amoludage** [gmailgem/gmail#204]
Hello @johnnyshields 

I'm trying some operations on my `gmail` account using this gem, but some methods doesn't work properly.

Below methods does not work for me.
- unspam!
- undelete!
- unarchive

**Comment by johnnyshields** [comment]
@amoludage I believe this is related to other open issues, e.g.

https://github.com/gmailgem/gmail/issues/160
https://github.com/gmailgem/gmail/issues/185

This needs debugging and better tests.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
