### ISSUE TITLE
save_to_file not working

### ISSUE THREAD

**Issue by gbailey4** [gmailgem/gmail#206]
When I try the following-
Save just the first attachment from the newest unread email (assuming pdf):
```Ruby
email = gmail.inbox.find(:unread).first
email.attachments[0].save_to_file("/path/to/location")
```
I get the following error
```Ruby
NoMethodError: undefined method `save_to_file' for #<Mail::...
```

Is this method not available?

**Comment by amoludage** [comment]
Hello @gbailey4 

This gem doesn't support `save_to_file` method.

To save such attachments you can try below code.


      email.attachments.each do |attachment|
          file = File.new("attachments/" + attachment.filename, "w+")
          file << attachment.decoded
          file.close
      end

Hope this will help you, Thanks :blush:

**Comment by gbailey4** [comment]
Can that be removed from the readme? That's a bit confusing. This did get
it working, however, I appreciate it!

**Comment by amoludage** [comment]
Yes I think this should be remove from readme.

@owners what do you think?

**Comment by bootstraponline** [comment]
fixed by https://github.com/gmailgem/gmail/issues/207
