### ISSUE TITLE
`text_part` data not received

### ISSUE THREAD

**Issue by amoludage** [gmailgem/gmail#208]
Hello, 

   I'm using `deliver` method for sending emails and it works fine when I'm sending emails using either
`text_part` or `html_part` option.

But It can not work with both the options in single message(i.e Example from README file)

```
gmail.deliver do
   to "email@example.com"
   subject "Having fun in Puerto Rico!"
   text_part do
     body "Text of plaintext message."
   end
   html_part do
     content_type 'text/html; charset=UTF-8'
     body "<p>Text of <em>html</em> message.</p>"
   end
end
```

When I send email like above example then I only received the `html_part` data, `text_part` data is missing from received email.

I also tried by changing the sequence of `html_part` & `text_part` but I only received `html_part`.

any help appreciated?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
