### ISSUE TITLE
Sign-in attempt prevented

### ISSUE THREAD

**Issue by amoludage** [gmailgem/gmail#209]
Hello,

I'm trying to login with `gmail` but I'm not able to login, I got `email` into my inbox i.e 

```
 Sign-in attempt prevented.

 Hi Amol,
    Someone just tried to sign in to your Google Account test123@gmail.com from an app,
    that doesn't    meet modern security standards.
    - -
    - -
   Google stopped this sign-in attempt, but you should review your recently used devices:
```

Any help??

**Comment by cowboygneox** [comment]
Google's advice is as follows: https://support.google.com/accounts/answer/6010255?hl=en

**Comment by cowboygneox** [comment]
However, if someone knows how to conform to Google's "security standards", it would be nice to integrate into this gem.

**Comment by cowboygneox** [comment]
However, for something like this, maybe OAuth is the way to go. Credentials are becoming less of a trusted source anyway....

**Comment by NazarK** [comment]
direct link for turn on "Access for less secure apps" https://www.google.com/settings/security/lesssecureapps

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
