### ISSUE TITLE
How to send mail with inline image and insert link?

### ISSUE THREAD

**Issue by elangovan-selvaraj** [gmailgem/gmail#212]
Please help me to send mail with inline image and link..

**Comment by amoludage** [comment]
Hello @elangovan91 

please try this solution

    gmail = Gmail.new('test@gmail.com', 'password')

    gmail.deliver do
       to "testuser@gmail.com"
       subject "attached image and link"
       body "test gmail mails https://github.com/gmailgem/gmail"
       add_file "path_of_image_file/images.jpg"
    end

Added link into mail `body` and used `add_path` for image 

Hope this helps.

Thanks :blush:

**Comment by elangovan91** [comment]
Thanks for your help @amoludage. Attach a file and insert link is working fine. I want insert image as inline also. We have two option to add a image in compose gmail. One is attachment and another one is inline. I want inline function..

**Comment by amoludage** [comment]
@elangovan91 not completely understand the meaning of ` inline ` images.

But there is another option that you can send images i.e using `html_part` option

See Example:

    gmail.deliver do
      to "testuser@gmail.com"
      subject "attached image inline"
      html_part do
        content_type "text/html; charset=UTF-8"
        body "<p>Text</p> <img src='http://www.planwallpaper.com/static/images/9-credit-1.jpg' >"
      end
    end

Thanks

**Comment by elangovan91** [comment]
![screen shot 2016 01 14 at 8 00 00 pm](https://cloud.githubusercontent.com/assets/7815693/12327055/4ffab932-bafa-11e5-857c-151515b51341.png)

I attached a screenshot for your reference. Your previous code is working for inline image via url. I want via upload a new image and insert photo as a inline.

**Comment by amoludage** [comment]
Ok :+1: 

I'll check and let you know if I found any solution for this.

**Comment by elangovan91** [comment]
Hi @amoludage 
    could you find for the solution for this issue?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
