### ISSUE TITLE
How do I get the recipients of an email?

### ISSUE THREAD

**Issue by SamuilDichev** [gmailgem/gmail#213]
Hi,

I'm writing a script to look for certain patterns in emails and respond automatically. One of the things I need it to be able to check for, is the recipients of the email. How do I get those? 

I'm getting all specific emails
```ruby
GMAIL.inbox.find(:unread, from: SENDER_EMAIL).each do |email|
```

And then I do stuff, among which I do `email.to`, which returns just this -
```
[#<struct Net::IMAP::Address name=nil, route=nil, mailbox="someemail", host="gmail.com">, #<struct Net::IMAP::Address name=nil, route=nil, mailbox="anotheremail", host=yahoo.com">]
```
Where the recipients are `someemail@gmail.com` and `anotheremail@yahoo.com`
So how do I get those out of this string of text? I suppose I could match them with a regex or something, but I'd rather there were a better way. So, is there?

**Comment by amoludage** [comment]
@SamuilDichev 

Try this i.e `email.message.to` instead of `email.to`

Example:

    gmail = Gmail.new(email, password)

    gmail.inbox.find(:unread, from: 'test@gmail.com').each do |email|
      email.message.to
    end

Hope this helps..

Thanks :blush:

**Comment by SamuilDichev** [comment]
@amoludage, that worked great! Thanks. I also used `email.message.from` to made a small reply-all function. 
```
def create_reply(subject, recipients, senders)
  GMAIL.compose do
    to recipients + senders - ["myemail@gmail.com"]
    subject "RE: #{subject}"
    body "Cheers for the lunch!"
  end
end
```
They give free lunch some times at work and the first to claim it gets it, so I use this in a bigger script made to automatically claim it for me :P Thanks for the help.
