### ISSUE TITLE
Compose message and save it to drafts

### ISSUE THREAD

**Issue by MindRave** [gmailgem/gmail#217]
Hello everyone!

Discovered this amazing gem, and it looks great for a project I'm about to undertake. However, I was curious whether this kind of functionality is supported/easily doable. I apologise in advance if I overlooked something - I looked at the code and the documentation, and didn't find anything related.

I'd like to compose an email and instead of sending it, save it to the Drafts folder. Is that possible? If yes, can someone point me in the right direction/method?

Thank you in advance!

**Comment by rizalmuthi** [comment]
I would love this too..

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
