### ISSUE TITLE
No attachments found when sent from Yahoo and filename has no extension?

### ISSUE THREAD

**Issue by faelsoto** [gmailgem/gmail#218]
Hello,

I'm on 0.6.0 and I'm having some issues with the gem, as I'm receiving emails from Yahoo with a filename without extension (the file name is `noname`), and when I try to access the attachment method, it is returned empty.

This behaviour is consistent within that email, if I download the attachment and send it through a Gmail account, the attachment is found. However, if that email is forwarded, the problem persists, so I think it might be an issue with the headers and not with the file.

How can I provide the information required to test and analyze this issue? Should I post the header information or should I send it to one specific Gmail account?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
