### ISSUE TITLE
 undefined method `connect' for Gmail:Class

### ISSUE THREAD

**Issue by adarsh-why** [gmailgem/gmail#221]
I am getting this error  "undefined method `connect' for Gmail:Class" while using connect method to connect gmail. However, when i use the keyword new instead of connect, then its working. And another thing is that when I use "new" instead of connect, I can't give all the xauth parameters since I am getting error saying "3 arguments instead of 2"

**Comment by Shwetakale** [comment]
@adarsh-why Which version of this gem are you using? I tried with version ```0.6.0``` and Its working fine.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
