### ISSUE TITLE
Can't connect using password or xoauth2

### ISSUE THREAD

**Issue by bradenwright** [gmailgem/gmail#222]
I want to use this gem but have been unable to login in via either method.

1) Password, I have tried turning on gmails "Access for less secure apps" https://github.com/gmailgem/gmail/issues/209 , still password doesn't work.  I've tried many formats but no avail.  I always get.

```
/rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):019:0> gmail = Gmail.connect!('fake.user@gmail.com', 'mypassword')
Gmail::Client::AuthorizationError: Couldn't login to giv ven Gmail account: fake.user@gmail.com (Invalid credentials (Failure))
    from /opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response'
    from /opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
    from /opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
    from /opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/net/imap.rb:436:in `login'
    from /opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gmail-0.6.0/lib/gmail/client/plain.rb:12:in `login'
    from /opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:54:in `login!'
    from /opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gmail-0.6.0/lib/gmail.rb:67:in `new!'
    from (irb):19
    from /opt/rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

I've also tried:

```
gmail = Gmail.connect!('fakeuser@gmail.com', 'mypassword')
gmail = Gmail.connect!('fake.user', 'mypassword')
gmail = Gmail.connect!('fake.user', 'mypassword')
```

2) I'vet tried different xoauth2 setups and can't get that either... Docs page shows:

```
gmail = Gmail.connect(:xoauth, "email@domain.com", 
  :token           => 'TOKEN',n
  :secret          => 'TOKEN_SECRET',
  :consumer_key    => 'CONSUMER_KEY',
  :consumer_secret => 'CONSUMER_SECRET'
)
```

`gmail = Gmail.connect(:xoauth2, 'email@domain.com', 'ACCESS_TOKEN')`
I was trying the first one more... but didn't know what fields are which.  When I followed the instructions on gmail it had a json like this https://developers.google.com/api-client-library/ruby/guide/aaa_client_secrets

```
{
  "installed": {
    "client_id": "837647042410-75ifg...usercontent.com",
    "client_secret":"asdlkfjaskd",
    "redirect_uris": ["http://localhost", "urn:ietf:oauth:2.0:oob"],
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token"
  }
}
```

I don't know which fields in json map to `:token, :secret, :consumer_key, :consumer_secret`, and guessing/googling hasn't helped me get by it.

I know https://github.com/gmailgem/gmail/issues/165 is open too.  Any help would be greatly appreciated.

**Comment by DidiRaggio** [comment]
Copy the zipped oauth2.rb file into your project. Fill in the client_id and client secret that you got from the google console. Run it in your terminal, follow the instructions and that should generate your token and refresh_token

**Comment by YossiCohen** [comment]
@DidiRaggio How can I use the token & the refresh_token?
Just put it as `ENV['GMAIL_TOKEN']` in:
`gmail = Gmail.connect(:xoauth2, "email@domain.com", ENV['GMAIL_TOKEN'])`
what if it will need to be refreshed?
what about the refresh token?

how to use this properly?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
