### ISSUE TITLE
Issue with some symbols in a subject

### ISSUE THREAD

**Issue by Frylock13** [gmailgem/gmail#223]
Hi. I'm on 0.6.0 and I'm having an issue with an incorrect subject. If the subject of email contains the symbol `:` I get an error when I try to decode parts - `undefined method `decoded' for nil:NilClass`

```
2.3.1 :028 > gmail.inbox.emails(:unread).first.parts[0]
 => nil
```

If you remove that symbol and resend, everything is fine
```
2.3.1 :030 > gmail.inbox.emails(:unread).first.parts[0]
 => #<Mail::Part:70199821365720, Multipart: false, Headers: <Content-Type: text/plain; charset=UTF-8>, <Content-Transfer-Encoding: base64>>
```

Could you help me?

**Comment by amoludage** [comment]
Hi @Frylock13  

I have tried this with the version `0.6.0`

Example:

The subject is like this =>  `This is :test :symbol`

Method Call =>

`gmail.inbox.emails(:unread).first.parts[0]`

Result =>

`#<Mail::Part:45519560, Multipart: false, Headers: <Content-Type: text/plain; charset=UTF-8>>`

So basically I'm not able to reproduce this bug.

Can you please add your mail `subject` in which you  are getting the error??

**Comment by Frylock13** [comment]
@amoludage Sure, `Number S:00000181321 Т:0303037`

**Comment by amoludage** [comment]
@Frylock13 Tried with this `subject` but still its working for me.

**Comment by Frylock13** [comment]
@amoludage Ok, I got it. It happens if email had been read and then marked as unread. I don't know this is bug or not :)

**Comment by Frylock13** [comment]
@amoludage Ok, now I'm confused. It's not because of an incorrect subject, label, etc. I get this error only from a certain email address. How to debug this weird issue? :)
