### ISSUE TITLE
Undefined method peek

### ISSUE THREAD

**Issue by Crisfole** [gmailgem/gmail#224]
Looks like the advertised 'peek' doesn't work. A quick peek at the code shows only the `attr_accessor :peek` line, but no other references to the attribute.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
