### ISSUE TITLE
Cannot login or connect

### ISSUE THREAD

**Issue by veekram** [gmailgem/gmail#225]
Gmail::Client::AuthorizationError: Couldn't login to given Gmail account: xxxxxxx@gmail.com (Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure))
from /Users/bikram/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response' .

I went through google support. Couldn't come up with anything at all.

**Comment by Shwetakale** [comment]
@veekram Which version of the gem you are using? And can you add some more steps so that someone looking into it will be able to reporoduce this issue.

I am using version```gmail-0.6.0``` and following method and I am able to connect

    Gmail.connect(username, password)

**Comment by veekram** [comment]
@Shwetakale I am using `gmail-0.6.0` as well. I tried to connect with `Gmail.connect(username, password)` . Do we need to configure some other as well?
`
[1] pry(main)> require 'gmail'
true
[2] pry(main)> Gmail.connect('veekramsuwal@gmail.com', 'xxxxx')
#<Gmail::Client0x7f9e9524c558 (veekramsuwal@gmail.com) disconnected>
[3] pry(main)>
`
This is what I get.

**Comment by Shwetakale** [comment]
@veekram Did you get any email on your account regarding  "Review blocked sign-in attempt"? Becuase when I sign in using account which has not given permission to less secure app I get same. This response can also get when password is incorrect. Read [this](http://www.digitbin.com/google-suspicious-sign-in-attempt-prevented/) for more details.

**Comment by skd86** [comment]
Is there another solution?

I know the solution is to turn on "allow less secure apps". However as noted in the text this is not a good option for security concerns.

**Comment by mackermedia** [comment]
As noted in #226, creating an "App password" (via steps here: https://www.lifewire.com/get-a-password-to-access-gmail-by-pop-imap-2-1171882) solved this issue for me.

**Comment by pencerw** [comment]
Note,  you need to have 2FA turned *on* (which should disable "allow less secure apps") in order to even access the App Password screen. But once I enabled 2FA and created an App Password, this issue was fixed for me.
