### ISSUE TITLE
How to connect verified gmail accounts.

### ISSUE THREAD

**Issue by SagareGanesh** [gmailgem/gmail#226]
Hi,
 I have set 2-step verification to my gmail account i.e when I try to login my account, gmail sends otp for login on my registered mobile . But when I tried to login through this gem, It gives me following error

`Gmail::Client::AuthorizationError: Couldn't login to given Gmail account:xxxxxxxxxxxxxxx@gmail.com (Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure))
`

Is there any way to login such accounts?
thanks

**Comment by Shwetakale** [comment]
@SagareGanesh  This gem use IMAP for connecting to gmail so so may be you will have to allow password authentication for IMAP. I haven't tried this but came across [this](http://email.about.com/od/gmailtips/fl/How-to-Get-a-Password-to-Access-Gmail-By-POP-or-IMAP.htm) post. Hope this will solve your problem.

**Comment by SagareGanesh** [comment]
@Shwetakale  Thanks for this post [How to Get a Password to Access Gmail By POP/IMAP (2-Step Verification Enabled)
](http://email.about.com/od/gmailtips/fl/How-to-Get-a-Password-to-Access-Gmail-By-POP-or-IMAP.htm) They have explained it very well.
thanks.
