### ISSUE TITLE
Review blocked sign-in attempt	

### ISSUE THREAD

**Issue by SagareGanesh** [gmailgem/gmail#227]
When i tried to login through gmail, Google sent me following mail.

## **Review blocked sign-in attempt.**

Google just blocked someone from signing into your Google Account
from an app that may put your account at risk.

### Less secure app
Thursday, September 22, 2016 6:29 PM (India Standard Time)
Pune, Maharashtra, India*

can anyone explain me what is reason behind it.

**Comment by Shwetakale** [comment]
@SagareGanesh As per [this] (https://productforums.google.com/forum/#!topic/gmail/1LAEHZpqMb8) now gmail requires "'modern' higher-security OAuth2 authentication during sign-in". And you are logging in using your email and password (i.e third party login) so probably you are getting this. For more details read [this] (http://www.digitbin.com/google-suspicious-sign-in-attempt-prevented/).

**Comment by SagareGanesh** [comment]
@Shwetakale yes, you are right. All Google accounts now require _**modern**_ higher-security OAuth2 authentication during sign-in. Conclusion is, use _**XOAuth authentication**_ for login instead of _**Direct username password**_, its more secure.
thanks.
