### ISSUE TITLE
Gmail stopped supporting full month names

### ISSUE THREAD

**Issue by cynektix** [gmailgem/gmail#228]
I encountered the problem today, that Gmail rejected my queries with dates (`on`, `before`, `after`) and after some digging I found the problem in the wrong implementation of the `to_imap_date` function.

As http://www.ietf.org/rfc/rfc3501.txt states the date format is

```
...
date = date-text / DQUOTE date-text DQUOE
...
date-text = date-day "-" date-month "-" date-year
...
date-month = "Jan" / "Feb" / "Mar" / "Apr" / "May" / "Jun" /
                  "Jul" / "Aug" / "Sep" / "Oct" / "Nov" / "Dec"
...
```

The implementation in the gem here uses `%B`, hence the full month names. However, it should use `%b` for the short month names.

I can fix this in my project by adding this snippet in my code:

```
class Object
  def to_imap_date
    date = respond_to?(:utc) ? utc.to_s : to_s
    Date.parse(date).strftime('%d-%b-%Y')
  end
end
```

**Comment by yuri-karpovich** [comment]
Works for me. Thank you!

**Comment by benjiebitium** [comment]
Works for me too. thanks so much

**Comment by annahiro** [comment]
IT Works ! thank you very much!

**Comment by evaldasg** [comment]
Thank you! It works!

**Comment by ruberzen** [comment]
Thanks!
