### ISSUE TITLE
Net::IMAP::BadResponseError: Could not parse command when filtering by date

### ISSUE THREAD

**Issue by faelsoto** [gmailgem/gmail#230]
Hi there,

It seems that there's an issue whenever `before`, `after` and `to` are used to filter emails. The response is `Net::IMAP::BadResponseError: Could not parse command`

Here's a sample code:

```
gmail = Gmail.new(email, password)
gmail.inbox.find(:unread) # this works
gmail.inbox.find(:unread, :before => Date.parse("2010-02-20")) # this doesn't
```

Maybe Gmail changed its parameters?

Thanks.

**Comment by atomgiant** [comment]
I am also seeing this behavior @faelsoto.  This also affects the `ruby-gmail` gem too which I started out on and switched to this gem to see if it fixes this issue.

Perhaps Gmail rolled out some changes that broke this?

**Comment by Guitaronin** [comment]
I'm having this problem as well. It began between 8pm and 9pm last night.

**Comment by Shwetakale** [comment]
@faelsoto @Guitaronin @atomgiant It seems to be Google now lo longer seems to accept full month name. It requires short month names.

Did you all check latest [pull request](https://github.com/gmailgem/gmail/pull/229) sent by @cynektix ? after using his branch my code started working as expected.

**Comment by cynektix** [comment]
For immediate monkey patch see https://github.com/gmailgem/gmail/issues/228

**Comment by syedhassan** [comment]
@cynektix gr8 work

**Comment by johnnygoodman** [comment]
@cynektix Worked for me, thank you!

**Comment by elearning1985** [comment]
I see this issue again. Error message :`get_tagged_response': Could not parse command (Net::IMAP::BadResponseError)

code that i was trying to execute:
      mailbox_obj.inbox.find(:after => Date.parse('2017-01-10')).each do |email|
        email.read!
      end
i need to use date time as the filter. Is there a way i can use this still? Could someone please reply?

**Comment by zenbalaji** [comment]
I am also getting this error again

`*** Net::IMAP::BadResponseError Exception: Could not parse command`

**Comment by cynektix** [comment]
@elearning1985 @zenbalaji did you even read through the whole thread?

I think this can be closed as it is resolved by https://github.com/gmailgem/gmail/pull/229

For a monkey patch solution until the next release is made see https://github.com/gmailgem/gmail/issues/228

**Comment by hvuong** [comment]
Was this every resolved? It seems to still be happening on 0.6.0

**Comment by peterfication** [comment]
If you compare the PR date of the [fix](https://github.com/gmailgem/gmail/pull/229), Jan 27 2017, and the release date of [0.6.0](https://github.com/gmailgem/gmail/releases/tag/v0.6.0), Aug 24 2015, you realise that the fix hasn't been released yet.

So you have to use the master branch.

**Comment by hvuong** [comment]
I'm installing this through ruby gem, will i need to manually build it instead?

**Comment by peterfication** [comment]
You can either put this in the Gemfile:

```ruby
gem 'gmail', git: 'https://github.com/gmailgem/gmail'
```

or even reference a specific commit hash directly:

```ruby
gem 'gmail', git: 'https://github.com/gmailgem/gmail', ref: '4f78039e9821340a24ad3d840180d2ec6c6e0115'
```

or you leave your Gemfile as it is and look here for the monkey patch solution: https://github.com/gmailgem/gmail/issues/228

**Comment by mhluska** [comment]
This is still not working for me. I've tried both the latest master gem and the monkey patch solution. I'm using an account that is part of G Suite. I've enabled less secure apps for the account.

**Comment by peterfication** [comment]
Do you have a problem with specifying a date for a query or doesn't the gmail gem work in general for you?

**Comment by mhluska** [comment]
The gem itself is not working when `gmail.inbox` is called. I guess I've posted in the wrong issue now that you mention it.

**Comment by peterfication** [comment]
@johnnyshields I think this issue can be closed as the fix is merged into master.

**Comment by benebrice** [comment]
Must use `master` branch.

```
# Gemfile.rb

gem 'gmail', git: 'git://github.com/gmailgem/gmail.git', branch: 'master'

```

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
