### ISSUE TITLE
imap.rb:1198:in `get_tagged_response': Unknown command h18mb374317qvb (Net::IMAP::BadResponseError)

### ISSUE THREAD

**Issue by gipsh** [gmailgem/gmail#232]
Hi Guys, 

I get the  error with this simple code, 

```
gmail = Gmail.connect($username, $password)
puts gmail.inbox.count
```
Running ubuntu 14.04.4 , gmail 0.6.0 and mail 2.64 and ruby 2.3.0p0 

Same code on ubuntu 15.10 with ruby 2.3.1p112 works fine. 

The full error stacktrace is 
```

/home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1198:in `get_tagged_response': Unknown command h18mb374317qvb (Net::IMAP::BadResponseError)
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:454:in `block in select'
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:452:in `select'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:207:in `switch_to_mailbox'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:164:in `block in mailbox'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:161:in `synchronize'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:161:in `mailbox'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/gmail-0.6.0/lib/gmail/client/base.rb:184:in `inbox'
	from get-mail.rb:9:in `<main>'
```

**Comment by trejkaz** [comment]
Is there a workaround for this? I'm getting it too, but I even tried updating to ruby 2.4.0 and it keeps happening.

**Comment by WuTheFWasThat** [comment]
happening to me too :(

**Comment by rempargo** [comment]
Either two of the following can be the reason for this:

- You did not enable IMAP in Gmail settings
- You did not set 'Allow less secure apps' on ON

See also attached screenshots.
**Gmail settings:**
<img width="1076" alt="enable_imap_in_settings" src="https://user-images.githubusercontent.com/261394/32328051-f427bd4a-bfd8-11e7-911c-255c93425168.png">

**Google account Settings:**
<img width="1248" alt="configure_less_secure_apps" src="https://user-images.githubusercontent.com/261394/32328052-f43f2926-bfd8-11e7-982f-2c2a07f8e375.png">

**Comment by trejkaz** [comment]
Both of those were on and I ultimately had to enable 2-factor authentication to get it to work at all.

**Comment by fguillen** [comment]
I have all on: 

- IMAP in Gmail settings
- 'Allow less secure apps'
- 2-factor authentication

Still I see the error:

```
.rbenv/versions/3.0.2/lib/ruby/3.0.0/net/imap.rb:1226:in `get_tagged_response': Unknown command z8mb388673000wrg (Net::IMAP::BadResponseError)
```

:/

This combination doesn't work either: 

- ON: IMAP in Gmail settings
- ON: 'Allow less secure apps'
- OFF: 2-factor authentication
