### ISSUE TITLE
Gem_version_bump

### ISSUE THREAD

**Issue by TBOUnderdog** [gmailgem/gmail#236]
While you guys have merged in the date format fix, you didn't bump the gem version so we have no way of getting it without directly referencing the github page.

Resolution: Bump Gem Version to 0.6.1

**Comment by kowal** [comment]
Guys, 1st of all - thanks for great library!

My question is similar - is there a plan for releasing new version? There seems to be couple of important fixes in `master`.

Thanks!

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
