### ISSUE TITLE
Net::IMAP::BadResponseError after 5 requests or so

### ISSUE THREAD

**Issue by gabeodess** [gmailgem/gmail#238]
I have this working in my application, however, after I make somewhere around 5 requests with `email.delete!` or `email.read!` I start to receive `Net::IMAP::BadResponseError` errors.  After I wait a bit of time it begins responding properly again.

Any idea why this might be happening?  Are there some query limits I need to adjust somewhere?

**Comment by kartikluke** [comment]
@gabeodess Did you figure it out?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
