### ISSUE TITLE
can we Accept/Decline a invite using this gem?

### ISSUE THREAD

**Issue by sureshpathipati** [gmailgem/gmail#239]
can someone tell me a way to do this

I am able to read and know the multi-type of a message, I am not able to proceed further to do RSVP action.

It would be great if someone share's knowledge regarding this.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
