### ISSUE TITLE
Conversation API

### ISSUE THREAD

**Issue by trejkaz** [gmailgem/gmail#240]
The logic I have in mind for my use of this gem is going to be applied per-conversation. It turns out that grouping by conversation is particularly slow right now:

      time("Just fetching emails") do
        puts "Number of emails: #{gmail.inbox.emails(:unread).count}"
      end

      time("Fetching and grouping emails by thread") do
        gmail.inbox.emails(:unread).group_by(&:thread_id).each do |thread_id, emails|
          puts "Thread #{thread_id}, emails #{emails.size}"
        end
      end

Timing:

    $ ./test.rb 
    Number of emails: 34
    Just fetching emails: 1.061151
    Fetching and grouping emails by thread: 38.848531

A little over a whole second to fetch each individual email. What makes this particularly horrible is that you can't process a single conversation until you have fetched every single email. (Or can you? It isn't actually clear. If it returned the messages grouped by conversation... then I guess you could process them as they arrive.)

According to [the docs](https://developers.google.com/gmail/imap_extensions), Gmail has an extension to fetch X-GM-THRID for a range of messages, so I guess you could pass that for the entire range of the mailbox, which should be a lot faster than 1 second per message.

Ignoring the performance issue, it would still help the API seem more like actual Gmail if it treated Conversation as part of the model, because many of the operations currently on Message in this API are actually on Conversation in the world of Gmail itself.

      gmail.conversations(:unread).each do |conversation|
        conversation.subject         # definitely useful

        conversation.initiator         # probably useful, but could look at the first message too
        conversation.participants  # not sure if it's that useful

        conversation.emails.each { |email| ... }
        conversation.emails(:unread).each { |email| ... }

        conversation.labels
        conversation.add_label('$Processed')
      end

**Comment by krschacht** [comment]
I too wanted Conversations to be modeled. Rather than extending the library itself, as a quick first step I created my own Conversation class which instantiate by iterating over all the messages. I put it here, in case it's helpful: https://github.com/gmailgem/gmail/wiki

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
