### ISSUE TITLE
Get message ID ?

### ISSUE THREAD

**Issue by MathieuDerelle** [gmailgem/gmail#241]
Is it possible to retrieve the message ID used in this API : https://developers.google.com/gmail/api/v1/reference/users/messages/get
i.e.
`https://www.googleapis.com/gmail/v1/users/{userId}/messages/{id}`

Gmail::Message#uid or msg_id dont do the job

**Comment by unkrich** [comment]
Not certain about this, but have you tried "variableName.message.id" without quotes?

**Comment by unkrich** [comment]
Take a look at #242

**Comment by MathieuDerelle** [comment]
It wasn't working. But i've found out what's going on.
This gem is giving the message_id as an integer : 1520524314001511398
and the API mentionned above is given it as an hexadecimal string : 1519fcceb86793e6
`1520524314001511398.to_s(16) == 1519fcceb86793e6 # => true`

**Comment by march23** [comment]
do the search as message_id: integer_message_id.to_s(16) it will work

**Comment by jparedesimx** [comment]
email.message.message_id.to_s
