### ISSUE TITLE
Image attachments are faulty after downloading.

### ISSUE THREAD

**Issue by BiTinerary** [gmailgem/gmail#248]
```
email.message.attachments.each do |attachment|
        folder = Dir.pwd
        File.write(File.join(folder, attachment.filename), attachment.body.decoded)
```

Part of the code I'm using. Attachments seem to download just fine. I can decode/parse **.txt** file attachments but not jpgs. Ruby creates pictures (`filename.jpg`) in the proper directory and everything as you'd expect. However, when opening an image, in any image viewing program, it is unrecognizable. I've tried saving pure Base64 code as jpeg, opening file with "wb" properties and writing raw code to file, and decoding using other methods, with the same results. This is on Windows OS.

Any ideas on how to download attached jpegs/images? Or some other workaround?

Update: The only way I can get a working jpeg is if (**on a linux machine**) I download it as mentioned above.

- Open the encoded, broken .jpg (**not** `attachment.body.decoded`) in a text editor.
- Strip off the header info. Read raw jpeg code from a python script, import Base64. 
- Then write to new file with `base64.b64decode(file)`.

Since decoding works using Base64 python library, does this indicate that there's an issue when calling the `decoded` function in ruby gmail library? Or is this user error?

**Comment by BiTinerary** [comment]
Solved. Basically scratch everything mentioned above.

I systematically went through writing jpgs both as decoded and encoded base64. As raw text files as well as with **and** without header. Nothing worked but if I copy/pasted and encoded base64 (without header) into a online base64 > image converter, it would work.

So I tried all the same processes, just on a linux (Orangepi Zero v1.4 running up-to-date Armbian) machine and the manually generated image was recognizeable in addition to using the `gmail` recommended source code. ie: 'attachment.body.decoded' So all is well but for other Windows users out there, expect this issue.

I'm certain it's to do with how ruby/python write to a file on windows vs linux. That is Windows uses `\r\n` and linux uses (reasonable) `\n`. That being said I tried multiple attemps to `chomp, strip(), split(), gsub()` any newlines while executing on Windows, to no avail.

Good thing I don't need to download jpeg attachments to a windows machine :P

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
