### ISSUE TITLE
Is it possible to forward emails using gmailgem? 

### ISSUE THREAD

**Issue by joshdance** [gmailgem/gmail#253]
Couldn't find it in the documentation.

**Comment by praveen576** [comment]
@joshdance : I am also looking for the same. forwarding specific message.

Using gmail ruby client, it is possible to create a filter with filter action forward, that also has some limitations. like
1. needs verified forwarding email address, So, verified address may be fine for bulk forwarding messages but for single message, it should not be a compulsion.

2.  can't apply filter on existing matching messages.

If you find something, please update here.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
