### ISSUE TITLE
Unable to extract the emails which are received in last 5 minutes

### ISSUE THREAD

**Issue by bishal52** [gmailgem/gmail#257]
I wanted to extract the emails which are received in last 5 minutes using gmail gem.

     Gmail.connect(email, password) do |gmail|                                                                   
       p gmail.inbox.find(:after => Time.zone.now - 5.minutes).count
     end

But its giving all the emails which are received today.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
