### ISSUE TITLE
Fetching emails with Google's Gmail API Client (for longer then few days)

### ISSUE THREAD

**Issue by Paxa** [gmailgem/gmail#261]
I'm watching and fetching emails in my app with `client.inbox.wait ...`, and considering switch to use Google's official Gmail API Ruby Client (as README suggests).

According to this docs https://developers.google.com/gmail/api/guides/push#watch_request, we should re-authenticate access to email every 7 days (or every day as recommended). Also access token, used to access inbox content will expire after even shorter time (cmiiw)

Is there any solution for this problem?

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
