### ISSUE TITLE
Maintenance of gem

### ISSUE THREAD

**Issue by dannnylo** [gmailgem/gmail#262]
Hello @jonpierce, @radar, @mikker, @gerhard, @bb

I'm interested in maintaining this gem of this gem. 
I plan keep the gem format and works with google api.

**Comment by radar** [comment]
## Deprecation Notice

> As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.

From the README

**Comment by dannnylo** [comment]
Hello @radar,
I want to continue this gem, because the form of google api gem works is too ugly and to hard to learn and use.
Then I want keep the code style with this gem and make the gem works through the google api gem.
