### ISSUE TITLE
Update README :after method must be replaced by :since method

### ISSUE THREAD

**Issue by guilhermenunes09** [gmailgem/gmail#266]
In the example:
`gmail.inbox.count(:after => Date.parse("2010-02-20"), :before => Date.parse("2010-03-20"))`
It seems that the attribute "after" does not exist anymore. The right replacement would be "since"

**Comment by johnnyshields** [comment]
Our lib uses `after` as the option here. `SINCE` is the native Gmail API.  https://github.com/gmailgem/gmail/blob/c5e938942675fb3a3f71fa957e299a1cd1ee1577/lib/gmail/mailbox.rb#L35
