### ISSUE TITLE
Couldn't login to given GMail account: user@gmail.com

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#30]
_From @webdevotion on July 19, 2011 10:0_

Every once and a while ( local dev machine ) I run into this problem.
No idea what is causing it.

```bash
Couldn't login to given GMail account: user@gmail.com
```

My code running in a controller:

```ruby
    begin
      logger.info("log in")
      gmail = Gmail.connect!('user@gmail.com','44444444444')
      @emails = gmail.inbox.find(:from => "*@domain.tld", :after => Date.parse("2011-07-10")).reverse
    rescue Exception => exc
      logger.error("could not get to the emails: #{exc.message}")
    ensure
      
    end
```

I would be more than happy to provide more debug information.

* Ruby 1.8.7 p 352
* Ruby On Rails 2.3.8
* Using RVM

```bash

gem list gmail

*** LOCAL GEMS ***

gmail (0.4.0)
gmail_xoauth (0.3.0)
```

_Copied from original issue: nu7hatch/gmail#30_

**Comment by bootstraponline** [comment]
_From @kennethjohnbalgos on August 7, 2011 9:23_

I also have the same problem. I think it has something to do with the Gmail connection session. I noticed that I am having this problem when my code is running multiple times with minimal intervals. I already tried to find a way to let my Gmail connect once then access the account in different controllers. But I failed. :( Right now, I'm running the Gmail.connect! every time I will access my inbox. But after several accesses, the error comes out. I wish that it will be resolved soon. Thanks!

**Comment by bootstraponline** [comment]
_From @nu7hatch on August 17, 2011 18:34_

I will check it out

**Comment by bootstraponline** [comment]
_From @webdevotion on August 18, 2011 9:32_

Kennethjohnbalgos has described the problem very well - identical issues.
Thanks for having a look.

**Comment by bootstraponline** [comment]
_From @jgrevich on March 5, 2012 4:7_

I haven't looked at the code behind this, but it may have something to do with too many simultaneous connections being made to google.  Does it help if you logout/close the connection after you set @emails?

**Comment by johnnyshields** [comment]
From @ryannealmes:

> I had this same issue and it seems google blocks any non google applications. You have to enable un-secure applications - such as this gem.
>
> To fix go to https://myaccount.google.com/security and update your security settings to 'Allow less secure apps: ON'
>
> After checking the documentation again, it actually tells you to do this there! Shows I should read more documentation.
>
> Hope that helps.

**Comment by slash4** [comment]
TIP : I found that Google sends an email shortly after the first connection attempt through the gem. This email includes this link : https://accounts.google.com/DisplayUnlockCaptcha. I HAD to navigate to this URL and activate the "unsecure app" to get connected.
