### ISSUE TITLE
'Net::IMAP::BadResponseError'  >>> unknown command

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#36]
_From @syntaxTerr0r on September 4, 2011 3:36_

This error occurs randomly while using the lib.

The exact problem is well described here : http://stackoverflow.com/questions/6385276/unknown-command-on-gmail-gem

I'm trying to get my emails using the Gmail gem (source) with the next call:

```ruby
class MyClass
  def initialize account, credentials
    @gmail = Gmail.connect(account, credentials)
  end

  def get_attachments received_at, options
    mails = @gmail.inbox.find(
      :to => options[:to],
      :has=>:attachments,
      :before => options[:end_date],
      :after => received_at
     )
     #more code
   end
end
```

@gmail is a valid instance of Gmail class, and this call raises sometimes the next error:

_Unknown command v2if4084974eef.9_

The command (v2if4084974eef.9) changes in every call I make.

What am I doing wrong?

I'm using ruby-1.9.2-p180 and rails 3.1.0

_Copied from original issue: nu7hatch/gmail#36_

**Comment by bootstraponline** [comment]
_From @faraazkhan on February 24, 2012 20:6_

folks any updates on this I keep getting the same error...

**Comment by bootstraponline** [comment]
_From @ryanlchan on July 9, 2012 0:5_

Yet another getting the same error. Peculiarly, this has intensified once moving to a Mac.

**Comment by bootstraponline** [comment]
_From @faraazkhan on July 9, 2012 0:19_

The error (for me at least) seemed to be related to some sort of limitation on google's side. I was able to reduce the frequency by forcing the app to end the session with gmail after sending each email...it still happens though..much less frequently.

**Comment by bootstraponline** [comment]
_From @ryanlchan on September 25, 2012 20:29_

I've revisited this issue today and think that it's a matter of thread safety, a la #34. In my testing, I only get this when using a multi-threaded approach, either in Unicorn or Girl_Friday. The switch to Mac corresponded with an upgraded processor/ssd, which compounded the thread race conditions.

**Comment by bootstraponline** [comment]
_From @tonyarkles on October 5, 2012 2:29_

I was experiencing something similar:
```
/Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/net/imap.rb:1143:in `get_tagged_response': Unknown command l22if5573897yhk.157 (Net::IMAP::BadResponseError)
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/net/imap.rb:1195:in `block in send_command'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/net/imap.rb:1177:in `send_command'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/net/imap.rb:437:in `block in select'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/net/imap.rb:435:in `select'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:199:in `switch_to_mailbox'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:157:in `block in mailbox'
	from <internal:prelude>:10:in `synchronize'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /Users/aja042/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:177:in `inbox'
	from ./circulate:15:in `<main>'
```

by running this code:

```ruby
user = User.first

gmail = Gmail.connect(user.username, user.password)

c = gmail.inbox.count
puts "Email count: #{c}"
```

This was consistent though; I couldn't ever successfully log in. I figured out the solution to my problem though: I've recently turned on Google's 2-factor authentication. By going into my account and generating an application-specific password, I've successfully logged in and retrieved the inbox count. This might not be what's affecting everyone, but it solved my problem.

**Comment by bootstraponline** [comment]
_From @dcu on October 10, 2012 4:5_

I am getting the same error however this only happens with one of my accounts, the others work fine

**Comment by bootstraponline** [comment]
*From @neohunter on Nov 22, 2012*

same error to me, seems to happen only on heroku.

this is the code:

```ruby
        m = self.account.gmail.deliver! do
        to message.to
        bcc message.bcc unless message.bcc.nil?
        subject message.subject
        text_part do
          content_type "text/plain; charset=utf-8"
          body message.body
        end
        html_part do
          content_type 'text/html; charset=UTF-8'
          body message.body_html
        end
      end
```

And the error:

```
Couldn't deliver email: 502 5.5.1 Unrecognized command. zx18sm1243799veb.3
/app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:130:in `rescue in deliver'
/app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:127:in `deliver'
/app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:135:in `deliver!'
/app/app/models/scheduled_message.rb:45:in `send_msg'
/app/app/models/scheduled_message.rb:38:in `block in send_all'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.1.3/lib/active_record/relation.rb:15:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.1.3/lib/active_record/relation.rb:15:in `each'
/app/app/models/scheduled_message.rb:38:in `send_all'
Im not sure of how to debug this error,
```

**Comment by bootstraponline** [comment]
*From @neohunter on Nov 22, 2012*

Happens always on heroku, im unable to replicate on local,

I enabled debug and this is what it show:

S: * OK Gimap ready for requests from 23.20.52.235 eb8if3194274vdb.70
C: RUBY0001 LOGIN email@gmail.com mypassword
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE
S: RUBY0001 OK email@gmail.com Some Email authenticated (Success)
Couldn't deliver email: 502 5.5.1 Unrecognized command. zx18sm2007420veb.3
/app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:130:in rescue in deliver' /app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:127:indeliver'
/app/vendor/bundle/ruby/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:135:in deliver!' /app/app/models/scheduled_message.rb:45:insend_msg'
/app/app/models/scheduled_message.rb:38:in `block in send_all'
....

**Comment by bootstraponline** [comment]
*From @matellis on Jan 7, 2013*

Seems like there might be two separate issues: one related to thread safety, the other to two factor authentication. I had this exact same issue and it was because I had accidentally revoked the app-specific credentials while cleaning up. It would be great if the gem could give a more helpful error message when this happens (attempting to login using an invalid password, or using the master password when two factor auth is turned on).

**Comment by bootstraponline** [comment]
*From @ryanlchan on Jan 26, 2013*

I'm thinking the problem is just due to an authentication failure - the thread safety issue I described is probably rate limiting as @faraazkhan described. Situations I've found to cause errors (both on Heroku and locally) are:

Running multiple simultaneous connections
Establishing several new connections in a short period of time
Using the master password in 2-factor situations
The error seems to arise somewhere between the greeting and sending the first command; in my experience, the random string appended to the greeting (e.g. eb8if3194274vdb.70 from @neohunter's example above) and and the command in the BadResponseError are the same.

Typically, waiting 5-10 minutes will fix the rate limiting. However, I'm struggling to see a way to differentiate rate-limiting errors from 2-factor errors.

**Comment by johnnyshields** [comment]
I'm closing this as it looks like the error is coming from Gmail itself, and the only known solution is to catch the error on the implementer side. Being a heavy user of this gem here are the errors I see/catch:

```
Net::IMAP::ByeResponseError
Net::IMAP::NoResponseError
Net::IMAP::BadResponseError
Gmail::Client::ConnectionError
OpenSSL::SSL::SSLError
Errno::ECONNRESET
EOFError
IOError
```
