### ISSUE TITLE
How to retreive uid of an email we just sent ?

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#39]
_From @slash4 on September 12, 2011 17:9_

Hi, 

i'm trying to get the uid (the gmail one) of an email I've just sent with the method deliver!

Is it possible to get this info without polling Gmail just after sending ?

Thanks, Alex

_Copied from original issue: nu7hatch/gmail#39_

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 15, 2015 13:10_

This is discussed here: #43. I've merged support to master.

**Comment by jordan-realfoto** [comment]
@bootstraponline Can you explain how this is possible? I don't see any reference in the documentation or the code relating to fetching the guid of an email composed and delivered via deliver!

Thanks.

**Comment by bootstraponline** [comment]
I just copied the issue contents over from the old repo, I didn't author those messages.

I moved on to using the official Google Ruby gem for working with the gmail API.
