### ISSUE TITLE
Gmail Message ID

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#43]
_From @jnarowski on October 19, 2011 19:50_

Do you ever plan to add support for searching by message_id? This is not the email thread id, but the the Gmail frontend message id of the message (this is a 64-bit hexadecimal value, different from the RFC 822 Message-ID).

This is provided to Google Apps and contextual gadgets, and the message can be retrieved using this ID as follows:
http://code.google.com/apis/gmail/imap/#x-gm-msgid

I am not sure if the Ruby IMAP library supports it or what would be necessary to add it, but if this could be added that would be awesome. 

_Copied from original issue: nu7hatch/gmail#43_

**Comment by johnnyshields** [comment]
_From @github0013 on November 4, 2011 4:17_

I googled some and found these.

http://rubyforge.org/pipermail/sup-devel/2011-May/001122.html
http://www.lesnikowski.com/blog/index.php/tag/x-gm-thrid/

as far as I understand, ruby's pure imap implimentation does not cover the Gmail extended commands you pointed out.
http://code.google.com/intl/ja/apis/gmail/imap/#x-gm-msgid
the raw Net::IMAP will give you a ResponseParseError exception if you try.

they did a monkey patch for this problem.
http://rubyforge.org/pipermail/sup-devel/attachments/20110517/ae523a7c/attachment.bin

if you require the monkey patch "module Net", then you can fetch x-gm-msgid like this

```ruby
require "the_monkey_patch_imap.rb"
gmail = Gmail.connect "id", "pass"
gmail.label("where_you_want_to_check")

#conn: Net::IMAP
#1: sequential email number in the mailbox
#data: Net::IMAP::FetchData
# http://www.ruby-doc.org/stdlib-1.9.2/libdoc/net/imap/rdoc/Net/IMAP.html#method-i-fetch
data = gmail.conn.fetch(1, "(X-GM-MSGID)")

#this will give you hex gm id, which should match with what it is in address bar when you open the same email in gmail
puts data.attr["X-GM-MSGID"].to_s(16)
```

**Comment by johnnyshields** [comment]
_From @jnarowski on November 4, 2011 14:24_

Thanks a lot. I ended up getting it to work by doing this...

email = gmail.mailbox("[Gmail]/All Mail").emails(:all, :query => ['X-GM-MSGID', converted_message_id])

**Comment by johnnyshields** [comment]
_From @github0013 on November 5, 2011 4:13_

how did you get your "converted_message_id" by the way?

**Comment by johnnyshields** [comment]
_From @jnarowski on November 8, 2011 21:12_

puts MSGID.to_i(16)

**Comment by johnnyshields** [comment]
_From @webcracy on October 4, 2013 18:12_

This is achieved in https://github.com/90seconds/gmail/commit/35e13e0409ba77a75c7cc4d06b60eed335ddb74c and  https://github.com/90seconds/gmail/commit/650f5968e591e6d320d391ac278c690e39854841, so we should definitely bring it to the gem.

**Comment by johnnyshields** [comment]
I've merged in the 90seconds fork, hence closing this issue.

**Comment by unkrich** [comment]
For some reason when I call .to_i(16) on my hex id I get an error that says Net::IMAP::DataFormatError: number must be unsigned 32-bit integer

Any idea how to fix? Thanks!
