### ISSUE TITLE
Download all mails without attachment

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#86]
_From @vpoulain on April 17, 2013 22:8_

Hello ! 
First of all, thank you for this great job.
I want to download all mails from gmail to process them but it's very slow. For example I've done : 

```
        gmail = Gmail.connect("login","pass")
        mails = gmail.inbox.emails(:read)
        person = Hash.new(0)

        mails.each { |mail|
            // processing
        }
```

I thin it is very slow because I download mail with attachment ? Can I skip that ?
Thank you !

_Copied from original issue: nu7hatch/gmail#86_

**Comment by vic-snippets** [comment]
Hi Guys, 
Like @vpoulain I am also having "slow" processing when reading messages that have attachments.
    `gmail.label("MyLabel").emails.each do |email|`
    `pp email.message.body.decoded`
    `end`
This prints the body and the all attachments. So when you have several a PDFs attached to the email it takes a while for the script to process.

Thank you for your time.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
