### ISSUE TITLE
How to search for emails and permanently delete them?

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#87]
_From @ssubashini17 on April 25, 2013 18:22_

Hi,
I was looking for ways to permanently delete emails after applying filters. Does the gem support it now?

I know delete! moves them to trash, but once an email is received with the same subject line the emails from trash are moved to their original folder again.

Thanks!

_Copied from original issue: nu7hatch/gmail#87_

**Comment by bootstraponline** [comment]
_From @nu7hatch on August 7, 2013 7:23_

Hi, sorry for late reply, I've been quite out of this project for a while. As i look at the code this is not supported now, and it may be tricky to actually do this easily. Let me sit down and think if it's worth effort.

**Comment by amoludage** [comment]
Hello @bootstraponline ,

The statement from first comment in this issue i.e `I know delete! moves them to trash, but once an email is received with the same subject line the emails from trash are moved to their original folder again` is not true.

I have checked this with deleting one message from inbox and send same message content again to this mailbox, but the message which is moved to `trash` was not moved to `inbox` again, that message still present in `trash`.

Gmail service message deletion strategy is as bellow statement -

` The messages that have been in Bin(Trash) for more than 30 days will be automatically deleted.`

OR we need to delete messages from `Trash(Bin)` as well for permanently deletion.

Thanks.

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
