### ISSUE TITLE
How to search -label:somelabel

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#90]
_From @grossadamm on July 29, 2013 13:23_

I'm trying to search for emails that do not have a certain label. Typically in gmail you would search for `-label:somelabel`. I'm not sure how to accomplish the same thing here.

I've tried both of these without luck.

    gmail.inbox.find(:query => ["-label:#{environment}"]) # error: Could not parse command
    gmail.inbox.find({"-label" => environment}) # finds all emails not just those without the label

_Copied from original issue: nu7hatch/gmail#90_

**Comment by bootstraponline** [comment]
_From @grossadamm on July 29, 2013 17:30_

I have a couple processes running that read the email, each process adds a
label to the email so that the same process does not run against the email
again.

So, I need to search for messages that are NOT in a given label. For
example, if I have five emails but one is labeled `coolLabel` in gmail I
can do a search for `-label:coolLabel` and it will give back the other four
emails. A not equal to logic as opposed to equal to logic.


On Mon, Jul 29, 2013 at 11:59 AM, Alexandre Loureiro Solleiro <
notifications@github.com> wrote:

> I think you just need to consider that labels are like folders, so instead
> of searching for labeled emails in the inbox, you can just navigate to that
> label/folder and access/manage/search the emails in there.
>
> gmail.mailbox('your_label').count
>
> —
> Reply to this email directly or view it on GitHub<https://github.com/nu7hatch/gmail/issues/90#issuecomment-21729660>
> .
>



-- 
--

Adam Gross

**Comment by bootstraponline** [comment]
_From @nu7hatch on August 7, 2013 7:14_

This mechanism is not possible with current implementation. To achieve it we'd have to use gmail's IMAP extension:

https://developers.google.com/gmail/imap_extensions#extension_of_the_search_command_x-gm-raw

I've been away from this code for quite a while, let me organize the mess that's in the issues and figure out the roadmap for this project.

**Comment by bootstraponline** [comment]
_From @kingdonb on April 8, 2014 13:59_

I was actually looking for a feature like this, but even worse:

I want to find each message from "[Gmail]/All Mail" that does not occur in any other label/folder.

In other words searching for label:unlabeled
This is not even possible in the Gmail web interface; the only way would be to run a search excluding all existing labels and then perhaps put the label:unlabeled on those mails for later processing.  So maybe if you ran through each label and kept a running tally of message ids, subtracting as you go from the uids in "[Gmail]/All Mail"...

**Comment by johnnyshields** [comment]
X-GM-RAW is now supported, hence closing this issue.
