### ISSUE TITLE
How do you delete a single message (not entire thread)

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#92]
_From @justinleveck on August 11, 2013 9:44_

Anyone know how? :)

_Copied from original issue: nu7hatch/gmail#92_

**Comment by bootstraponline** [comment]
_From @webcracy on October 4, 2013 17:0_

This is currently not supported, as per the comment on #87 :(

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
