### ISSUE TITLE
add imap idle method to wait for new messages

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#93]
_From @wstrinz on October 4, 2013 15:24_

I added a small feature that uses IMAP IDLE, which has a method supporting it in the standard library IMAP implementation. I've written it to return when a new message is received, so you can use it to avoid repeatedly polling your inbox. You should also be able to pass a block that gets executed on new messages, but I didn't have time to write a test for it so I'm not sure if that bit works.

There's also the issue of IDLE timing out after 30 min, the code I adapted this from wraps the whole `imap.idle` block in a loop and has a separate thread that closes and reopens the connection -

````ruby
loop do
  Thread.new do
    puts "Starting timer"
    sleep 29 * 60
    imap.idle_done
  end
  
  imap.idle do |r|
     # etc
  end
end
````

but I'm not sure this is the best way to handle it, so I've left the timeout handling out here.

_Copied from original issue: nu7hatch/gmail/pull/93_

**Comment by bootstraponline** [comment]
_From @webcracy on October 4, 2013 16:48_

Thanks for working on this. I'll do my best to give it a try and add more feedback.

**Comment by bootstraponline** [comment]
_From @wstrinz on October 4, 2013 20:28_

Thanks for looking it over, I'll see if I can tie the mailbox selection in to Gmail::Label in case https://github.com/nu7hatch/gmail/pull/83 gets merged.

**Comment by johnnyshields** [comment]
Refer to PR #136
