### ISSUE TITLE
Searching Superstars

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#94]
_From @afomi on October 14, 2013 1:17_

Is it possible to search for Superstars like "red-bang"?  In Gmail, 'has:red-bang' works as an advanced search filter (https://support.google.com/mail/answer/7190).  I'm not sure if this is a .gem or API limitation.

_Copied from original issue: nu7hatch/gmail#94_

**Comment by johnnyshields** [comment]
This should now be doable using `gm:` search option which exposes Gmail's native search interface via the `X-GM-RAW` flag.
